teams:
  - name: team1
    namespace: team-1-namespace
    networkPolicy:
      enabled: true
    resourceQuota:
      enabled: true
      cpu: "4"
      memory: 8Gi
    projectRole: admin
  - name: team2
    namespace: team-2-namespace
    networkPolicy:
      enabled: true
    resourceQuota:
      enabled: true
      cpu: "1"
      memory: 2Gi
    projectRole: edit
  - name: team3
    namespace: team-3-namespace
    networkPolicy:
      enabled: false
    resourceQuota:
      enabled: false

