{{- range .Values.teams }}
{{- if and (hasKey . "networkPolicy") (and (hasKey .networkPolicy "enabled") .networkPolicy.enabled) }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .name }}-deny-by-default
  namespace: {{ .name }}
spec:
  podSelector:
    ingress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .name }}-allow-same-namespace
  namespace: {{ .name }}
spec:
  podSelector:
    ingress:
      - from:
        - podSelector: {}
{{- end }}
{{- end }}


