{{- range .Values.teams }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .name }}-{{ .projectRole | default "admin" }}-rolebinding
  namespace: {{ .namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .projectRole | default "admin" }}
subjects:
  - kind: Group
    name: {{ .name }}
    apiGroup: rbac.authorization.k8s.io
{{- end }}
